### ISSUE TITLE
currently just changing the rating but not taking avg. We need to store all the other past ratings in the DB to be able to do the average

### ISSUE THREAD

**Issue by KinetekEnergy** [Project-MKAAT/backend-MKAAT#7]
```
                    # TODO
```

https://github.com/Project-MKAAT/backend-MKAAT/blob/eb04ad27c9e1910b5025afd32607a926d01c9698/api/anime.py#L65

**Comment by trevorhuang1** [comment]
Figured out code logic for user rating. We need to store as a json list in the database, and then convert from json to string, then string to float. After that, we can just sum all of the elements and divide by the total amount of elements :)

![image](https://github.com/Project-MKAAT/backend-MKAAT/assets/118785933/28574eda-4681-48bb-9c0f-c897a9495310)
![image](https://github.com/Project-MKAAT/backend-MKAAT/assets/118785933/b60260d6-8055-490e-b3f6-d8fb03a88fb8)

**Comment by trevorhuang1** [comment]
each rating is assigned with the user who rated so that it can be checked that the same person did not rate a show twice

![image](https://github.com/Project-MKAAT/backend-MKAAT/assets/118785933/fdad3962-9ab0-4fc0-afb6-c9591e785c1d)

**Comment by KinetekEnergy** [comment]
fixed it to take avg now.
